<a href="https://colab.research.google.com/github/aarpitdubey/tf_dev_certificate_dl_ztm/blob/main/1_DeepLearnin_and_TensorFlow_Fundamentals/1_TensorFlow_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 # Fundamental concepts of tensors using TensorFlow

 - Introduction to tensors
 - Getting information from tensors
 - Manipulating tensors
 - Tensor & NumPy
 - Using `@tf.function` (a way to speed up your regular Python functions)
 - Using GPUs with TensorFlow (or TPUs)
 - Exercises

## Introduction to Tensors

In [ ]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.15.0


`tf.constant()` : Creates a constant tensor from a tensor-like object.

In [ ]:
# Create tensors with tf.constant()

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

- scalar has zero dimensions,
- a vector has one dimension, and
-  a tensor can have multiple (n) dimensions.

`tensor.ndim` : return the number of dimensions of a given tensor

In [ ]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim # it's a scalar having 0 dimensions

0

In [ ]:
# Creating a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
# Check the dimension of the vector

vector.ndim

1

In [7]:
# Create a matrix (has more than one dimension)
matrix = tf.constant([[10, 7],
                                        [7, 10]])

matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [8]:
matrix.ndim

2

In [9]:
# Create another matrix

another_matrix = tf.constant([[10., 7.],
                                                        [3., 2.],
                                                        [8., 9.]], dtype=tf.float16) # specify the data type with dtype parameter

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [10]:
# Check the number of dimensions of another_matrix
another_matrix.ndim

2

In [11]:
# Let's create a tensor
tensor = tf.constant([[[1, 2, 3],
                                        [4, 5, 6]],
                                        [[7, 8, 9],
                                        [10, 11, 12]],
                                        [[13, 14, 15],
                                         [16, 17, 18]]])

tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [12]:
tensor.ndim

3

* Scalar: a single number
* Vector: a number with direction (e.g. wind speed and direction)
* Matrix: a 2-dimentional array of numbers
* Tensor: an n-dimentional